version: '3.1'
services:
  postgres:
    image: "postgres:13.2"
    hostname: "postgres"
    container_name: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
