version: '3.3'
services:
  postgres:
    image: "postgres:10"
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "redmine"
      PGDATA: "/var/lib/postgresql/data"
    restart: "always"

  redmine:
    image: "redmine:4.1.1"
    ports:
      - "3000:3000"
    volumes:
      - ./storage/redmine/plugins:/usr/src/redmine/plugins
      - ./storage/redmine/themes:/usr/src/redmine/public/themes
      - ./storage/redmine/data:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: "postgres"
      REDMINE_DB_USERNAME: "postgres"
      REDMINE_DB_PASSWORD: "password"
      REDMINE_DB_DATABASE: "redmine"
      REDMINE_SECRET_KEY_BASE: "secret"
    restart: always
