version: '3'

services:
  web:
    build: .
    ports:
      - "${DOKUWIKI_HTTP_PORT}:80"
    volumes:
      - ${DOKUWIKI_STORAGE}/data:/var/www/html/data
      - ${DOKUWIKI_STORAGE}/lib:/var/www/html/lib
      - ${DOKUWIKI_STORAGE}/conf:/var/www/html/conf
    restart: always
