version: '2'

services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    hostname: "zookeeper"
    container_name: "zookeeper"
    expose:
      - "2181"
  kafka:
    image: "wurstmeister/kafka"
    hostname: "kafka"
    container_name: "kafka"
    ports:
       - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  kafdrop:
    image: "obsidiandynamics/kafdrop"
    hostname: "kafdrop"
    container_name: "kafdrop"
    restart: "no"
    ports:
      - "${KAFDROP_PORT}:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
