version: '3.3'
services:
  elasticsearch:
    image: "elasticsearch:7.10.1"
    hostname: "elasticsearch"
    container_name: "elasticsearch"
    labels:
      name: "elasticsearch"
    # restart: "always"
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./storage/elasticsearch/data:/usr/share/elasticsearch/data

#volumes:
#  storage:
